version: '3.9'
services:
    nexus:
        user: root
        image: "sonatype/nexus3"
        ports:
            - "8081:8081"
            - "8082:8082"
        volumes:
            - "C:/Users/cbacilio/Documents/novopayment/ambiente/cbd/docker/volumes/nexus:/nexus-data"
        networks:
            - test-networks-local

networks:
    test-networks-local:
        driver: bridge