version: '3.8'
services:
    postgres-app:
        image: "postgres"
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
            timeout: 45s
            interval: 10s
            retries: 10
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - '5438:5432'
        volumes:
            - "C:/Users/cbacilio/Documents/novopayment/ambiente/cbd/docker/volumes/postgresql:/var/lib/postgresql/data"
        networks:
            - test-networks-local
networks:
    test-networks-local:
        driver: bridge