# Embedded Server configuration
server:
    #port: 8003
    port: ${PORT:0} #solo para auto scaling
    compression:
        enabled: true
    tomcat:
        uri-encoding: UTF-8
    error:
        include-stacktrace: never
# Spring configuration
spring:
    webflux:
        base-path: /microservices/v1
    application:
        name: microservice-militares
        version: 1.0.0
        log: /logs
    messages:
        encoding: UTF-8
    profiles:
        active:
            - test

    version: 2.7.7
    main:
        banner-mode: log
        lazy-initialization: false
    mvc:
        converters:
            preferred-json-mapper: jsonb
    jpa:
        open-in-view: false
        show-sql: true
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false
    datasource:
        initialization-mode: never
        hikari:
            connection-init-sql: SELECT 1
            connection-test-query: SELECT 1
            allow-pool-suspension: false
            auto-commit: true
            connection-timeout: 3000
            idle-timeout: 600000
            leak-detection-threshold: 45000
            max-lifetime: 1800000
            minimum-idle: 10
            maximum-pool-size: 20
            validation-timeout: 5000
        driverClassName: org.postgresql.Driver
        #password: ${password:}
        #username: ${username}
        #url: ${database}
        password: postgres
        username: postgres
        url: jdbc:postgresql://localhost:5438/postgres

# Configuration Eureka Server
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
# Logger Configuration
logging:
    level:
        root: INFO







# Logger Sleuth:
    sleuth:
        sampler:
            probability: 1.0
# Logger Zipkin:
    zipkin:
        base-url: http://localhost:9411/
